(require "asdf")
(require "cl-ppcre")
(load "/usr/lib/quicklisp/setup")
(quicklisp:quickload "drakma")

(format t "~{~a~^ ~}~%" (cdr sb-ext:*posix-argv*))
(setf fnam (format nil "~{~a~^-~}" (cdr sb-ext:*posix-argv*)))
(setf srch (format nil "~{~a~^+~}" (cdr sb-ext:*posix-argv*)))
(setf fnam (concatenate 'string fnam ".html"))
(with-open-file (fh fnam :direction :output :if-exists :supersede)
                (format fh "<h1>NOTICE: RMCCURDY.COM IS NOT RESPONSIBLE FOR ANY CONTENT ON THIS PAGE. THIS PAGE IS A RESULT OF IMAGES.GOOGLE.COM INDEXING AND NO CONTENT IS HOSTED ON THIS SITE. PLEASE SEND ANY COPYRIGHT NOTICE INFORMATION TO <a href=\"https://support.google.com/legal/contact/lr_dmca?dmca=images&product=imagesearch\">GOOGLE</a> OR THE OFFENDING WEBSITE</h1>~%")
                (format fh "<br>~%")
                (loop for i from 0 to 100 by 20 do
	                  (setf url (format nil "https://www.google.com/search?q=~a&safe=off&tbm=isch&ijn=0&start=~d" srch i))
	                  (setf content (drakma:http-request url))
	                  (setf content (cl-ppcre:regex-replace-all "<" content "
	<"))
	                  (setf contlines (cl-ppcre:split "\\n" content))
	                  (setf contlines (remove-if-not #'(lambda (line) (cl-ppcre:scan "imgurl" line)) contlines))
                      (mapcar #'(lambda (item)
                                  (setf item (cl-ppcre:regex-replace-all ".*imgurl=" item "<img src=\""))
                                  (setf item (cl-ppcre:regex-replace-all "&amp.*" item "\">"))
                                  (format fh item)
                                  (format fh "~%"))
                              contlines)))

(setf fo (uiop:read-file-lines fnam))
(delete-duplicates fo :test #'string-equal)
(with-open-file (ofh fnam :direction :output :if-exists :supersede)
                (mapcar #'(lambda (line)
                            (format ofh line)
                            (format ofh "~%"))
                        fo))
